<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ltcpond</groupId>
        <artifactId>msg-relay-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>msg-relay-starter</artifactId>
    <name>msg-relay-starter</name>
    <description>Application entry point</description>

    <dependencies>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-user</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-im</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-reliability</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-group</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ltcpond</groupId>
            <artifactId>msg-relay-search</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
